### ISSUE TITLE
Contact transfer support

### ISSUE THREAD

**Issue by anttileppa** [Metatavu/pakkasmarja-berries#91]
As an user  i would like to be have feature for synchronizing contacts from SAP into Keycloak.

**Comment by hkurhinen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Yhteystietojen synkronointi SAPista Keycloakiin (siirtotiedosto)](https://trello.com/c/KLLGDymW/1-yhteystietojen-synkronointi-sapista-keycloakiin-siirtotiedosto)
