### ISSUE TITLE
Monitor long term operation

### ISSUE THREAD

**Issue by anttileppa** [Metatavu/pakkasmarja-berries#92]
As an user i would like to be able to monitor progress of long term operations. As a part of this story a job queue is created

**Comment by hkurhinen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Yhteystietojen synkronointi SAPista Keycloakiin (siirtotiedosto)](https://trello.com/c/KLLGDymW/1-yhteystietojen-synkronointi-sapista-keycloakiin-siirtotiedosto)

**Comment by hkurhinen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sopimustietojen synkronointi SAPista palvelimelle (siirtotiedosto)](https://trello.com/c/xv2x7Zcp/3-sopimustietojen-synkronointi-sapista-palvelimelle-siirtotiedosto)

**Comment by hkurhinen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Toteumatietojen synkronointi SAPista palvelimelle (siirtotiedosto, automaattinen)](https://trello.com/c/MGsVGd4l/5-toteumatietojen-synkronointi-sapista-palvelimelle-siirtotiedosto-automaattinen)
