### ISSUE TITLE
Contact change notifications

### ISSUE THREAD

**Issue by anttileppa** [Metatavu/pakkasmarja-berries#93]
As a manager i would like to receive a notification when user changes his/her contact details

**Comment by hkurhinen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Yhteystietojen päivittäminen applikaatioon](https://trello.com/c/rvg1eeq3/6-yhteystietojen-p%C3%A4ivitt%C3%A4minen-applikaatioon)
