### ISSUE TITLE
Contract transfer support

### ISSUE THREAD

**Issue by anttileppa** [Metatavu/pakkasmarja-berries#95]
As an user i would like to be have feature for synchronizing contracts from SAP into the server

**Comment by hkurhinen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sopimustietojen hallinta](https://trello.com/c/S82ifp7L/4-sopimustietojen-hallinta)

**Comment by hkurhinen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sopimustietojen synkronointi SAPista palvelimelle (siirtotiedosto)](https://trello.com/c/xv2x7Zcp/3-sopimustietojen-synkronointi-sapista-palvelimelle-siirtotiedosto)
