### ISSUE TITLE
Delivery details synchronization

### ISSUE THREAD

**Issue by anttileppa** [Metatavu/pakkasmarja-berries#97]
As an user i would like to have up-to-date information about deliveries i've made related to specific contracts

**Comment by hkurhinen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Toteumatietojen synkronointi SAPista palvelimelle (siirtotiedosto, automaattinen)](https://trello.com/c/MGsVGd4l/5-toteumatietojen-synkronointi-sapista-palvelimelle-siirtotiedosto-automaattinen)
