### ISSUE TITLE
Electronic signature support

### ISSUE THREAD

**Issue by anttileppa** [Metatavu/pakkasmarja-berries#98]
As an user i would like to be able to use electronic signature services to sign my contracts

**Comment by hkurhinen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sähköinen allekirjoitus applikaatioon](https://trello.com/c/aiZyb9cE/7-s%C3%A4hk%C3%B6inen-allekirjoitus-applikaatioon)
