### ISSUE TITLE
Contract support

### ISSUE THREAD

**Issue by anttileppa** [Metatavu/pakkasmarja-berries#99]
As an user i would like to be able to list, find and update contracts via REST calls

**Comment by hkurhinen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sopimustyökalu applikaatioon](https://trello.com/c/bWVJQgbJ/8-sopimusty%C3%B6kalu-applikaatioon)

**Comment by hkurhinen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sopimustietojen hallinta](https://trello.com/c/S82ifp7L/4-sopimustietojen-hallinta)
